on:
  workflow_call:
    outputs:
      product-version:
        value: ${{ jobs.init.outputs.product-version }}
      product-version-major:
        value: ${{ jobs.init.outputs.product-version-major }}

jobs:

  init:
    name: Initialize
    runs-on: ubuntu-latest

    outputs:
      product-version: ${{ steps.version.outputs.product-version }}
      product-version-major: ${{ steps.version.outputs.product-version-major }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Get Version
        id: version
        working-directory: ./
        run: |
          productVersion=$(cat version.txt)
          majorVersion=$(echo "$productVersion" | cut -d'.' -f1)
          echo "product-version=$productVersion" >> $GITHUB_OUTPUT
          echo "product-version-major=$majorVersion" >> $GITHUB_OUTPUT
