name: Migration policy

on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]

permissions:
  contents: read

jobs:
  migration-policy:
    uses: mthalman/release-automation/.github/workflows/migration-policy.yml@dbda9774dde7b70af4eb22be7257ee9cd17c2d6f # v1.0.2
