name: Release draft

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-draft:
    uses: mthalman/release-automation/.github/workflows/release-draft.yml@dbda9774dde7b70af4eb22be7257ee9cd17c2d6f # v1.0.2
